version: "3.4"

services:
  nats:
    image: nats:latest
    container_name: nats_server
    restart: unless-stopped
    networks:
      - combined-network
    
  nats_worker:
    build: ./nats_worker
    container_name : nats_worker
    depends_on:
      - nats
    networks:
      - combined-network

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./static:/django_web/static
    ports:
      - "80:80"
    depends_on:
      - db
      - django_web
    networks:
      - combined-network

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: applications_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - combined-network

  django_web:
    build: ./django_web
    container_name: django_web
    volumes:
      - ./static:/django_web/static
    depends_on:
      - db
    networks:
      - combined-network

networks:
  combined-network:
    driver: bridge